require('dotenv').config()
const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
const authRoutes = require('./routes/auth')
const personsRoutes = require('./routes/persons')
const addressesRoutes = require('./routes/addresses')
const householdsRoutes = require('./routes/households')
const membersRoutes = require('./routes/members')
const incomesRoutes = require('./routes/incomes')
const qualificationsRoutes = require('./routes/qualifications')
const domicileRoutes = require('./routes/domicile_conditions')
const dependentsRoutes = require('./routes/dependents')
const healthRoutes = require('./routes/health_infos')
const incomeVerRoutes = require('./routes/income_verification')
const authMiddleware = require('./middleware/auth')
const app = express()
app.use(cors())
app.use(bodyParser.json())
app.get('/api/health', (req, res) => res.json({status: 'ok'}))
app.use('/api/auth', authRoutes)
app.use('/api/persons', authMiddleware, personsRoutes)
app.use('/api/addresses', authMiddleware, addressesRoutes)
app.use('/api/households', authMiddleware, householdsRoutes)
app.use('/api/members', authMiddleware, membersRoutes)
app.use('/api/incomes', authMiddleware, incomesRoutes)
app.use('/api/qualifications', authMiddleware, qualificationsRoutes)
app.use('/api/domicile', authMiddleware, domicileRoutes)
app.use('/api/dependents', authMiddleware, dependentsRoutes)
app.use('/api/health', authMiddleware, healthRoutes)
app.use('/api/income_verification', authMiddleware, incomeVerRoutes)
app.use((err, req, res, next) => {
  console.error(err)
  res.status(500).json({error: 'internal_error', message: err.message})
})
const PORT = process.env.PORT || 3000
app.listen(PORT, () => console.log('Server listening on', PORT))
